f = io.open('manual.html','r')
s = f:read('*a')
f:close()
w = io.open('org.lua.www.manual','wb')
string.gsub(s, '<a name="5.1">(.-)<a name="6">', function(s)
	string.gsub(s, '<a name="pdf-[^"]*"><code>([^(]-)</code></a></h3>%s*(.-)%s*<p>%s*<hr><h3>', function(funcName, description)
		w:write( funcName .. '=[====[\\n')
		w:write('<dt><a name="' .. funcName .. '"></a><strong>' .. funcName .. '</strong></dt>\\n')
		w:write('<dd>\\n', string.gsub(description, '\n', '\\n') , '\\n</dd>\\n')
		w:write(']====]\n\n')
	end)
	string.gsub(s, '<a name="pdf-[^"]*"><code>([^(<]-)[(]([^)]*)[)]</code></a></h3>%s*(.-)%s*<p>%s*<hr><h3>', function(funcName, funcParams, description)
		w:write( funcName .. '=[====[\\n')
		w:write('<dt><a name="' .. funcName .. '"></a><strong>' .. funcName .. '</strong>&nbsp;(' .. funcParams .. ')</dt>\\n')
		w:write('<dd>\\n', string.gsub(description, '\n', '\\n') , '\\n</dd>\\n')
		w:write(']====]\n\n')
	end)
end)
w:close()
